name = "noizylab"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "noizylab-repairs"
database_id = "350df477-a1d2-40cb-94c0-6d503a6b38c2"

[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "e318dd12863d491bb079b7dfa9510975"

[vars]
SITE_URL = "https://noizylab.ca"
