name = "database-systems-worker"
main = "worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB_SYSTEMS_DB"
database_name = "noizylab-database-systems"
database_id = "database-systems-db-id"

[[kv_namespaces]]
binding = "DB_CACHE"
id = "database-systems-cache-id"

[ai]
binding = "AI"
