name = "noizylab-creative-ai"
main = "worker.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "CREATIVE_AI_DB"
database_name = "creative-ai-db"
database_id = "creative-ai-db-id"

[[kv_namespaces]]
binding = "CREATIVE_AI_CACHE"
id = "creative-ai-cache-id"

[vars]
WORKER_NAME = "creative-ai"
