name = "noizylab-color-science"
main = "worker.ts"
compatibility_date = "2024-01-01"
[ai]
binding = "AI"
[[d1_databases]]
binding = "COLOR_DB"
database_name = "color-db"
database_id = "color-db-id"
[[kv_namespaces]]
binding = "COLOR_CACHE"
id = "color-cache-id"
[vars]
WORKER_NAME = "color-science"
